# Generated by Django 3.0.3 on 2020-02-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droidshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', editable=False, max_length=10),
        ),
    ]
